# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

before_script:
  - pip2.7 install --upgrade --ignore-installed --user travis pip setuptools wheel virtualenv
  - R CMD INSTALL .
  - R -e 'fable.prophet::install_prophet()'
